/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as paymentAccountSol from "./PaymentAccount.sol";
export type { paymentAccountSol };
import type * as pollSol from "./poll.sol";
export type { pollSol };
export * as factories from "./factories";
export type { IERC20 } from "./PaymentAccount.sol/IERC20";
export { IERC20__factory } from "./factories/PaymentAccount.sol/IERC20__factory";
export type { PaymentAccount } from "./PaymentAccount.sol/PaymentAccount";
export { PaymentAccount__factory } from "./factories/PaymentAccount.sol/PaymentAccount__factory";
export type { Ballot } from "./poll.sol/Ballot";
export { Ballot__factory } from "./factories/poll.sol/Ballot__factory";
